### ISSUE TITLE
Can't install rofi-1.6.0-1 in dom0: Error Unable to find a match/No package rofi available?

### ISSUE THREAD

**Issue by 3d73a4a412** [QubesOS-contrib/updates-status#37]
I am having other problems with installing rofi on dom0 on my other machine so am posting this since the errors i think are a bit different? As with my other box I have tried restarting VMs, restarting the computer, running updates for dnf and qubes-dom0-update etc but still not able to get rofi to install/work?

sudo qubes-dom0-update && sudo qubes-dom0-update qubes-repo-contrib && sudo dnf update && sudo dnf upgrade && sudo qubes-dom0-update rofi
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Fedora 25 - x86_64 - Updates                     14 MB/s |  24 MB     00:01    
Fedora 25 - x86_64                               13 MB/s |  50 MB     00:03    
Qubes OS Contrib Repository for dom0 (updates)   53 kB/s |  76 kB     00:01    
Qubes Dom0 Repository (updates)                 1.0 MB/s | 1.4 MB     00:01    
determining the fastest mirror (15 hosts).. done.--  B/s |   0  B     --:-- ETA
Qubes Templates repository                      2.7 kB/s | 5.6 kB     00:02    
Last metadata expiration check: 0:00:01 ago on Mon Dec 28 11:38:50 2020.
Dependencies resolved.
Nothing to do.
Complete!
No packages downloaded
Qubes OS Repository for Dom0                                                                   30 MB/s |  32 kB     00:00    
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Last metadata expiration check: 0:00:10 ago on Mon Dec 28 11:38:50 2020.
Package qubes-repo-contrib-4.0.6-1.fc25.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
No packages downloaded
Qubes OS Repository for Dom0                                                                   27 MB/s |  32 kB     00:00    
Package qubes-repo-contrib-4.0.6-1.fc25.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
Qubes OS Repository for Dom0                                                                   26 MB/s |  32 kB     00:00    
Dependencies resolved.
Nothing to do.
Complete!
Qubes OS Repository for Dom0                                                                   31 MB/s |  32 kB     00:00    
Dependencies resolved.
Nothing to do.
Complete!
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Last metadata expiration check: 0:00:17 ago on Mon Dec 28 11:38:50 2020.
Dependencies resolved.
================================================================================
 Package       Arch     Version         Repository                         Size
================================================================================
Installing:
 rofi          x86_64   1.6.0-1.fc25    qubes-contrib-dom0-r4.0-current   196 k
Installing dependencies:
 rofi-themes   noarch   1.6.0-1.fc25    qubes-contrib-dom0-r4.0-current    19 k

Transaction Summary
================================================================================
Install  2 Packages

Total download size: 215 k
Installed size: 549 k
DNF will only download packages for the transaction.
Downloading Packages:
(1/2): rofi-themes-1.6.0-1.fc25.noarch.rpm       28 kB/s |  19 kB     00:00    
(2/2): rofi-1.6.0-1.fc25.x86_64.rpm              73 kB/s | 196 kB     00:02    
--------------------------------------------------------------------------------
Total                                            78 kB/s | 215 kB     00:02     
warning: /var/lib/qubes/dom0-updates/var/cache/yum/x86_64/4.0/qubes-contrib-dom0-r4.0-current-f2dc85ad2c5beed9/packages/rofi-1.6.0-1.fc25.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID d0941e87: NOKEY
Qubes OS Contrib Repository for dom0 (updates)  1.7 MB/s | 1.7 kB     00:00    
Importing GPG key 0xD0941E87:
 Userid     : "Qubes OS Contrib Release 4 Signing Key"
 Fingerprint: 04A8 F986 B97F BCB8 38F0 8C30 5FE4 986A D094 1E87
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-contrib-fedora
Key imported successfully
Complete!
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
*** ERROR while receiving updates:
Error while verifying rofi-1.6.0-1.fc25.x86_64.rpm signature: /var/lib/qubes/updates/rpm/rofi-1.6.0-1.fc25.x86_64.rpm: (RSA) sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: RSA#d0941e87 (MD5) PGP#d0941e87) 

--> if you want to use packages that were downloaded correctly, use dnf directly now
[stranford@dom0 ~]$ sudo dnf install rofi
Failed to synchronize cache for repo 'qubes-dom0-cached', disabling.
No package rofi available.
Error: Unable to find a match.
[stranford@dom0 ~]$ sudo dnf install qubes-rofi
Failed to synchronize cache for repo 'qubes-dom0-cached', disabling.
No package qubes-rofi available.
Error: Unable to find a match.
[stranford@dom0 ~]$ sudo dnf clean packages
0 files removed

**Comment by fepitre** [comment]
This is not the place for such request. Please search on mail lists or discourse forum.
